import { env, SELF } from 'cloudflare:test';
import { beforeEach, describe, expect, it } from 'vitest';
import worker, { purge, type Env } from '../../worker';
import { blankDraft, type DraftInput, type OwnerRequest } from '../../shared/domain';

const origin='https://example.com';
let address=0;
class Client {
  cookies = new Map<string,string>(); ip=`192.0.2.${++address}`;
  async call(path:string,method='GET',data?:unknown,headers:Record<string,string>={}){
    const response=await SELF.fetch(`${origin}${path}`,{method,headers:{'CF-Connecting-IP':this.ip,...(method!=='GET'?{'Origin':origin,'X-CPL-Request':'1','Content-Type':'application/json'}:{}),Cookie:[...this.cookies].map(([k,v])=>`${k}=${v}`).join('; '),...headers},...(data===undefined?{}:{body:JSON.stringify(data)})});
    const set=response.headers.get('set-cookie');if(set){const[k,v]=set.split(';')[0]!.split('=');this.cookies.set(k!,v!);}return response;
  }
}
const draft=():DraftInput=>({...blankDraft(),businessName:'Fictional Fence Co.',businessContact:'owner@example.test',customerName:'Sample Customer',jobTitle:'Side gate addition',jobReference:'FICTIONAL-350',reason:'Requested during the fence job.',scope:'Supply and fit one additional side gate.',lineItems:[{description:'Side gate installation',quantity:1,unitPriceCents:35000}],schedule:{kind:'impact',details:'One additional working day.'},privateNotes:'OWNER-ONLY-SENTINEL'});
async function workspace(client=new Client()) { const response=await client.call('/api/workspaces','POST',{});expect(response.status).toBe(201);return{client,...await response.json() as {managementLink:string;workspace:{id:string}}}; }
async function saved(client:Client,d=draft()) {const response=await client.call('/api/requests','POST',{draft:d,idempotencyKey:crypto.randomUUID()});expect(response.status).toBe(201);return(await response.json() as {request:OwnerRequest}).request;}
async function published(client:Client,record:OwnerRequest){const response=await client.call(`/api/requests/${record.id}/publish`,'POST',{revision:record.revision,expiryDays:7,idempotencyKey:crypto.randomUUID()});expect(response.status).toBe(200);return await response.json() as {request:OwnerRequest;customerLink:string};}
async function customer(link:string,client=new Client()){const url=new URL(link),versionId=url.pathname.split('/').at(-1)!;const response=await client.call(`/api/review/${versionId}/exchange`,'POST',{token:url.hash.slice(1)});expect(response.status).toBe(200);return{client,versionId,response};}
const responseInput=(action='approved')=>({action,respondentName:'Sample Customer',comment:action==='changes_requested'?'Please widen the gate opening.':'',acknowledged:action==='approved',idempotencyKey:crypto.randomUUID()});

describe('actual Worker and D1 private workflow',()=>{
  beforeEach(async()=>{await env.DB.batch([env.DB.prepare('DELETE FROM workspaces'),env.DB.prepare('DELETE FROM rate_limits')]);});
  it('reuses a newly established owner session on uncertain workspace-create retry',async()=>{const a=await workspace();const retried=await a.client.call('/api/workspaces','POST',{});expect(retried.status).toBe(201);const value=await retried.json() as {workspace:{id:string};managementLink:string};expect(value.workspace.id).toBe(a.workspace.id);expect((await env.DB.prepare('SELECT COUNT(*) n FROM workspaces').first<{n:number}>())?.n).toBe(1);expect((await new Client().call('/api/recover','POST',{token:new URL(a.managementLink).hash.slice(1)})).status).toBe(401);});
  it('retries uncertain create and publish actions without adding duplicate requests or versions',async()=>{const a=await workspace();const input={draft:draft(),idempotencyKey:crypto.randomUUID()};const first=await a.client.call('/api/requests','POST',input);const initial=(await first.json() as {request:OwnerRequest}).request;const retry=await a.client.call('/api/requests','POST',input);expect((await retry.json() as {request:OwnerRequest}).request.id).toBe(initial.id);expect((await a.client.call('/api/requests','POST',{...input,draft:{...draft(),scope:'Changed payload.'}})).status).toBe(409);const publication={revision:initial.revision,expiryDays:7,idempotencyKey:crypto.randomUUID()};const p1=await a.client.call(`/api/requests/${initial.id}/publish`,'POST',publication);const original=await p1.json() as {request:OwnerRequest};const p2=await a.client.call(`/api/requests/${initial.id}/publish`,'POST',publication);expect(p2.status).toBe(200);const repeated=await p2.json() as {request:OwnerRequest;customerLink:string};expect(repeated.request.versions).toHaveLength(1);expect(repeated.request.versions[0]?.id).toBe(original.request.versions[0]?.id);await customer(repeated.customerLink);});
  it('extends owner recovery availability to every newly created request retention boundary',async()=>{const a=await workspace();await env.DB.prepare("UPDATE workspaces SET expires_at=strftime('%Y-%m-%dT%H:%M:%fZ','now','+1 day') WHERE id=?").bind(a.workspace.id).run();const r=await saved(a.client);const row=await env.DB.prepare('SELECT expires_at FROM workspaces WHERE id=?').bind(a.workspace.id).first<{expires_at:string}>();expect(row?.expires_at).toBe(r.retainUntil);});
  it('keeps two simultaneously active customer sessions and owner authorization independent',async()=>{const a=await workspace(),p1=await published(a.client,await saved(a.client)),p2=await published(a.client,await saved(a.client)),v1=await customer(p1.customerLink,a.client);expect((await a.client.call('/api/session')).status).toBe(200);expect((await a.client.call(`/api/review/${p2.request.versions[0]!.id}`)).status).toBe(401);const v2=await customer(p2.customerLink,a.client);expect((await a.client.call(`/api/review/${v1.versionId}`)).status).toBe(200);expect((await a.client.call(`/api/review/${v2.versionId}`)).status).toBe(200);expect((await a.client.call('/api/session')).status).toBe(200);});
  it('does not create storage on configuration/session GET and blocks missing CSRF',async()=>{const c=new Client();expect((await c.call('/api/config')).status).toBe(200);expect((await c.call('/api/session')).status).toBe(401);expect((await env.DB.prepare('SELECT COUNT(*) n FROM workspaces').first<{n:number}>())?.n).toBe(0);expect((await c.call('/api/workspaces','POST',{}, {Origin:'https://attacker.example'})).status).toBe(403);expect((await c.call('/api/workspaces','POST',{}, {'X-CPL-Request':''})).status).toBe(403);});
  it('persists across owner and customer contexts, keeps notes private, exports receipt',async()=>{
    const {client:owner}=await workspace();const record=await saved(owner);const pub=await published(owner,record);const {client:viewer,versionId,response}=await customer(pub.customerLink);
    expect(response.headers.get('cache-control')).toContain('no-store');expect(response.headers.get('referrer-policy')).toBe('no-referrer');expect(response.headers.get('set-cookie')).toContain('HttpOnly; Secure; SameSite=Strict');expect(await response.text()).not.toContain('OWNER-ONLY-SENTINEL');
    expect((await viewer.call('/api/requests')).status).toBe(401);expect((await owner.call(`/api/review/${versionId}`)).status).toBe(401);
    const result=await viewer.call(`/api/review/${versionId}/decision`,'POST',responseInput());expect(result.status).toBe(200);const receipt=await result.json() as {receipt:{action:string;decidedAt:string}};expect(receipt.receipt.action).toBe('approved');expect(receipt.receipt.decidedAt).toMatch(/Z$/);
    const reopened=await owner.call(`/api/requests/${record.id}`);expect((await reopened.json() as {request:OwnerRequest}).request.status).toBe('approved');
    const customerExport=await viewer.call(`/api/review/${versionId}/export`);const content=await customerExport.text();expect(content).toContain('35000');expect(content).not.toContain('OWNER-ONLY-SENTINEL');expect(content).not.toContain('token_hash');
    const ownerExport=await owner.call(`/api/requests/${record.id}/export`);expect(await ownerExport.text()).toContain('OWNER-ONLY-SENTINEL');
  });
  it('denies guessed IDs cross-workspace reads edits export delete and linked requests',async()=>{const a=await workspace(),b=await workspace();const r=await saved(a.client);for(const [path,method,data]of [[`/api/requests/${r.id}`,'GET',undefined],[`/api/requests/${r.id}/export`,'GET',undefined],[`/api/requests/${r.id}`,'PUT',{draft:draft(),revision:1}],[`/api/requests/${r.id}`,'DELETE',{revision:1}],[`/api/requests/${r.id}/publish`,'POST',{revision:1,expiryDays:7,idempotencyKey:crypto.randomUUID()}]] as const)expect((await b.client.call(path,method,data)).status).toBe(404);expect((await b.client.call('/api/requests','POST',{draft:{...draft(),linkedRequestId:r.id},idempotencyKey:crypto.randomUUID()})).status).toBe(404);});
  it('recovery rotates its capability and revocation clears every owner session',async()=>{const a=await workspace(),other=new Client();expect((await other.call('/api/recover','POST',{token:new URL(a.managementLink).hash.slice(1)})).status).toBe(200);const rotated=await a.client.call('/api/recovery/rotate','POST',{});const next=await rotated.json() as {managementLink:string};expect((await new Client().call('/api/recover','POST',{token:new URL(a.managementLink).hash.slice(1)})).status).toBe(401);expect((await a.client.call('/api/sessions/revoke','POST',{})).status).toBe(200);expect((await other.call('/api/session')).status).toBe(401);expect((await a.client.call('/api/recover','POST',{token:new URL(next.managementLink).hash.slice(1)})).status).toBe(200);});
  it('prevents stale autosaves and preserves immutable snapshots after settings and draft edits',async()=>{const a=await workspace();const r=await saved(a.client);const p=await published(a.client,r);const next={...draft(),scope:'Revised unpublished work.'};expect((await a.client.call(`/api/requests/${r.id}`,'PUT',{draft:next,revision:1})).status).toBe(409);expect((await a.client.call(`/api/requests/${r.id}`,'PUT',{draft:next,revision:p.request.revision})).status).toBe(200);await a.client.call('/api/settings','PUT',{businessName:'New business name',businessContact:'new@example.test',defaultExpiryDays:3});const view=await customer(p.customerLink);const data=await view.response.json() as {review:{snapshot:{scope:string;businessName:string}}};expect(data.review.snapshot.scope).toBe(draft().scope);expect(data.review.snapshot.businessName).toBe(draft().businessName);await expect(env.DB.prepare('UPDATE versions SET snapshot_json=? WHERE id=?').bind('{}',view.versionId).run()).rejects.toThrow('immutable_snapshot');});
  it('requires acknowledgment and useful changes, stores at most one decision, retries idempotently',async()=>{const a=await workspace(),r=await saved(a.client),p=await published(a.client,r),v=await customer(p.customerLink);const input=responseInput();expect((await v.client.call(`/api/review/${v.versionId}/decision`,'POST',{...input,acknowledged:false})).status).toBe(400);expect((await v.client.call(`/api/review/${v.versionId}/decision`,'POST',{...responseInput('changes_requested'),comment:'no'})).status).toBe(400);const first=await v.client.call(`/api/review/${v.versionId}/decision`,'POST',input);const second=await v.client.call(`/api/review/${v.versionId}/decision`,'POST',input);expect(first.status).toBe(200);expect(second.status).toBe(200);expect(await first.json()).toEqual(await second.json());expect((await v.client.call(`/api/review/${v.versionId}/decision`,'POST',responseInput('declined'))).status).toBe(409);expect((await env.DB.prepare('SELECT COUNT(*) n FROM decisions WHERE version_id=?').bind(v.versionId).first<{n:number}>())?.n).toBe(1);});
  it('atomically handles concurrent decisions and creates exactly one evidence event',async()=>{const a=await workspace(),p=await published(a.client,await saved(a.client)),v=await customer(p.customerLink);const responses=await Promise.all([v.client.call(`/api/review/${v.versionId}/decision`,'POST',responseInput()),v.client.call(`/api/review/${v.versionId}/decision`,'POST',responseInput('declined'))]);expect(responses.map(r=>r.status).sort()).toEqual([200,409]);expect((await env.DB.prepare("SELECT COUNT(*) n FROM events WHERE version_id=? AND kind IN ('approved','declined','changes_requested')").bind(v.versionId).first<{n:number}>())?.n).toBe(1);});
  it('races approval against revocation without rewriting a committed approval',async()=>{const a=await workspace(),p=await published(a.client,await saved(a.client)),v=await customer(p.customerLink);const responses=await Promise.all([v.client.call(`/api/review/${v.versionId}/decision`,'POST',responseInput()),a.client.call(`/api/requests/${p.request.id}/revoke`,'POST',{revision:p.request.revision})]);expect(responses.filter(r=>r.status===200)).toHaveLength(1);const current=(await (await a.client.call(`/api/requests/${p.request.id}`)).json() as {request:OwnerRequest}).request;if(current.status==='approved'){expect((await a.client.call(`/api/requests/${current.id}/revoke`,'POST',{revision:current.revision})).status).toBe(200);const final=(await (await a.client.call(`/api/requests/${current.id}`)).json() as {request:OwnerRequest}).request;expect(final.status).toBe('approved');expect(final.versions[0]?.decision?.action).toBe('approved');}else expect(current.status).toBe('revoked');expect((await v.client.call(`/api/review/${v.versionId}`)).status).toBe(401);});
  it('supersedes old outstanding review links and keeps recipient sessions scoped per version',async()=>{const a=await workspace(),r=await saved(a.client),p=await published(a.client,r),v=await customer(p.customerLink);const p2=await published(a.client,p.request);expect((await v.client.call(`/api/review/${v.versionId}/decision`,'POST',responseInput())).status).toBe(401);const other=await customer(p2.customerLink,v.client);expect(other.versionId).not.toBe(v.versionId);expect((await other.client.call(`/api/review/${other.versionId}`)).status).toBe(200);const row=(await (await a.client.call(`/api/requests/${r.id}`)).json() as {request:OwnerRequest}).request;expect(row.versions[0]?.status).toBe('superseded');});
  it('rotates review capabilities and denies both old raw tokens and old scoped sessions',async()=>{const a=await workspace(),p=await published(a.client,await saved(a.client)),v=await customer(p.customerLink);const rotation=await a.client.call(`/api/requests/${p.request.id}/link/rotate`,'POST',{revision:p.request.revision});expect(rotation.status).toBe(200);expect((await v.client.call(`/api/review/${v.versionId}`)).status).toBe(401);expect((await new Client().call(`/api/review/${v.versionId}/exchange`,'POST',{token:new URL(p.customerLink).hash.slice(1)})).status).toBe(401);await customer((await rotation.json() as {customerLink:string}).customerLink);});
  it('linearizes simultaneous capability rotation and decision with database-bound session authorization',async()=>{const a=await workspace(),p=await published(a.client,await saved(a.client)),v=await customer(p.customerLink);const original=await env.DB.prepare('SELECT token_hash,capability_hash FROM review_sessions WHERE version_id=?').bind(v.versionId).first<{token_hash:string;capability_hash:string}>();const results=await Promise.all([a.client.call(`/api/requests/${p.request.id}/link/rotate`,'POST',{revision:p.request.revision}),v.client.call(`/api/review/${v.versionId}/decision`,'POST',responseInput())]);expect(results.filter(r=>r.status===200)).toHaveLength(1);if(results[0]?.status===200){await expect(env.DB.prepare("INSERT INTO decisions(version_id,action,respondent_name,comment,acknowledged,idempotency_key,payload_hash,authorized_capability_hash,authorized_session_hash) VALUES(?,'approved','Sample Customer','',1,?,?,?,?)").bind(v.versionId,crypto.randomUUID(),'payload',original!.capability_hash,original!.token_hash).run()).rejects.toThrow('stale_decision');expect((await env.DB.prepare('SELECT COUNT(*) n FROM decisions WHERE version_id=?').bind(v.versionId).first<{n:number}>())?.n).toBe(0);}});
  it('linearizes revision publication against an old-version approval',async()=>{const a=await workspace(),p=await published(a.client,await saved(a.client)),v=await customer(p.customerLink);const edited=await a.client.call(`/api/requests/${p.request.id}`,'PUT',{draft:{...draft(),scope:'A different proposed scope.'},revision:p.request.revision});const current=(await edited.json() as {request:OwnerRequest}).request;const results=await Promise.all([a.client.call(`/api/requests/${current.id}/publish`,'POST',{revision:current.revision,expiryDays:7,idempotencyKey:crypto.randomUUID()}),v.client.call(`/api/review/${v.versionId}/decision`,'POST',responseInput())]);expect(results.filter(r=>r.status===200)).toHaveLength(1);const record=(await (await a.client.call(`/api/requests/${current.id}`)).json() as {request:OwnerRequest}).request;if(results[0]?.status===200){expect(record.currentVersion).toBe(2);expect(record.versions[0]?.decision).toBeNull();}else{expect(record.status).toBe('approved');expect(record.currentVersion).toBe(1);}});
  it('enforces session expiry at database decision insertion and review-link expiry at its exact boundary',async()=>{const a=await workspace(),p=await published(a.client,await saved(a.client)),v=await customer(p.customerLink);await env.DB.prepare("UPDATE review_sessions SET expires_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE version_id=?").bind(v.versionId).run();expect((await v.client.call(`/api/review/${v.versionId}/decision`,'POST',responseInput())).status).toBe(401);const trigger=await env.DB.prepare("SELECT sql FROM sqlite_master WHERE type='trigger' AND name='immutable_version'").first<{sql:string}>();await env.DB.exec('DROP TRIGGER immutable_version');try{await env.DB.prepare("UPDATE versions SET expires_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?").bind(v.versionId).run();}finally{await env.DB.prepare(trigger!.sql).run();}expect((await new Client().call(`/api/review/${v.versionId}/exchange`,'POST',{token:new URL(p.customerLink).hash.slice(1)})).status).toBe(401);const row=(await (await a.client.call(`/api/requests/${p.request.id}`)).json() as {request:OwnerRequest}).request;expect(row.status).toBe('expired');});
  it('rolls back workspace creation if its first owner session cannot be persisted',async()=>{await env.DB.exec("CREATE TRIGGER test_fail_session BEFORE INSERT ON owner_sessions BEGIN SELECT RAISE(ABORT,'test_storage_failure'); END;");try{expect((await new Client().call('/api/workspaces','POST',{})).status).toBe(503);expect((await env.DB.prepare('SELECT COUNT(*) n FROM workspaces').first<{n:number}>())?.n).toBe(0);}finally{await env.DB.exec('DROP TRIGGER test_fail_session');}});
  it('blocks all edits and republication of approved work',async()=>{const a=await workspace(),p=await published(a.client,await saved(a.client)),v=await customer(p.customerLink);await v.client.call(`/api/review/${v.versionId}/decision`,'POST',responseInput());const r=(await (await a.client.call(`/api/requests/${p.request.id}`)).json() as {request:OwnerRequest}).request;expect((await a.client.call(`/api/requests/${r.id}`,'PUT',{draft:draft(),revision:r.revision})).status).toBe(409);expect((await a.client.call(`/api/requests/${r.id}/publish`,'POST',{revision:r.revision,expiryDays:7,idempotencyKey:crypto.randomUUID()})).status).toBe(409);expect((await saved(a.client,{...draft(),linkedRequestId:r.id})).draft.linkedRequestId).toBe(r.id);});
  it('rolls back the response and state if an evidence write fails',async()=>{const a=await workspace(),p=await published(a.client,await saved(a.client)),v=await customer(p.customerLink);await env.DB.exec("CREATE TRIGGER test_fail_evidence BEFORE INSERT ON events WHEN NEW.kind='approved' BEGIN SELECT RAISE(ABORT,'test_storage_failure'); END;");try{expect((await v.client.call(`/api/review/${v.versionId}/decision`,'POST',responseInput())).status).toBe(503);expect((await env.DB.prepare('SELECT COUNT(*) n FROM decisions WHERE version_id=?').bind(v.versionId).first<{n:number}>())?.n).toBe(0);expect((await env.DB.prepare('SELECT status FROM versions WHERE id=?').bind(v.versionId).first<{status:string}>())?.status).toBe('awaiting');}finally{await env.DB.exec('DROP TRIGGER test_fail_evidence');}});
  it('enforces retention expiry independently of review expiry and purges dependent records',async()=>{const a=await workspace(),p=await published(a.client,await saved(a.client)),v=await customer(p.customerLink);await env.DB.prepare("UPDATE requests SET retain_until='2000-01-01T00:00:00.000Z' WHERE id=?").bind(p.request.id).run();expect((await v.client.call(`/api/review/${v.versionId}/decision`,'POST',responseInput())).status).toBe(401);expect((await a.client.call(`/api/requests/${p.request.id}`)).status).toBe(404);await purge(env as unknown as Env);for(const table of ['requests','versions','decisions','review_sessions','events'])expect((await env.DB.prepare(`SELECT COUNT(*) n FROM ${table}`).first<{n:number}>())?.n).toBe(0);});
  it('enforces explicit deletion with cascades and leaves another workspace untouched',async()=>{const a=await workspace(),b=await workspace(),p=await published(a.client,await saved(a.client));await saved(b.client);expect((await a.client.call(`/api/requests/${p.request.id}`,'DELETE',{revision:p.request.revision})).status).toBe(200);expect((await env.DB.prepare('SELECT COUNT(*) n FROM versions').first<{n:number}>())?.n).toBe(0);expect((await a.client.call('/api/workspace','DELETE',{confirmation:'DELETE'})).status).toBe(200);expect((await b.client.call('/api/requests')).status).toBe(200);expect((await a.client.call('/api/session')).status).toBe(401);});
  it('fails closed when production protection is not configured and enforces real server limits',async()=>{const request=new Request(`${origin}/api/workspaces`,{method:'POST',headers:{Origin:origin,'X-CPL-Request':'1','Content-Type':'application/json','CF-Connecting-IP':'198.51.100.200'},body:'{}'});const result=await worker.fetch(request,{...env,ENVIRONMENT:'production',ALLOW_TEST_PROTECTION:'true',TURNSTILE_SECRET_KEY:undefined,TURNSTILE_SITE_KEY:undefined} as unknown as Env);expect(result.status).toBe(503);const c=new Client();for(let i=0;i<5;i++)expect((await c.call('/api/workspaces','POST',{})).status).toBe(201);expect((await c.call('/api/workspaces','POST',{})).status).toBe(429);});
  it('hashes capabilities at rest, never reflects management secrets in exports, and rejects oversized bodies',async()=>{const a=await workspace();const raw=new URL(a.managementLink).hash.slice(1);const row=await env.DB.prepare('SELECT recovery_hash FROM workspaces WHERE id=?').bind(a.workspace.id).first<{recovery_hash:string}>();expect(row?.recovery_hash).toMatch(/^[a-f0-9]{64}$/);expect(row?.recovery_hash).not.toBe(raw);const r=await saved(a.client,{...draft(),scope:'<img src=x onerror=alert(1)> & <script>evil()</script>'});const output=await a.client.call(`/api/requests/${r.id}/export`);expect(output.headers.get('content-type')).toContain('application/json');expect(await output.text()).not.toContain(raw);expect((await a.client.call('/api/requests','POST',{draft:{...draft(),scope:'x'.repeat(70_000)},idempotencyKey:crypto.randomUUID()})).status).toBe(413);});
});
