import type { DraftInput, OwnerRequest, Price } from '../shared/domain';
import { calculatePrice } from '../shared/domain';
import { dateOnly, money } from './api';
import { Field, Icon } from './components';
import { Status } from './Document';

export function safePrice(draft: DraftInput): Price | null { try { return calculatePrice(draft); } catch { return null; } }

function Section({ number, title, note, children }: { number: string; title: string; note: string; children: React.ReactNode }) {
  return <section className="editor-section"><div className="editor-section-heading"><span className="section-number">{number}</span><div><h2>{title}</h2><p>{note}</p></div></div><div className="editor-section-content">{children}</div></section>;
}

export function Editor({ draft, request, onChange, onSave, onPreview, onPublish, busy, dirty, error, validation, firstTime, children }: { draft: DraftInput; request: OwnerRequest | null; onChange: (draft: DraftInput) => void; onSave: () => void; onPreview: () => void; onPublish: () => void; busy: boolean; dirty: boolean; error: string; validation: string[]; firstTime: boolean; children?: React.ReactNode }) {
  const set = <K extends keyof DraftInput>(key: K, value: DraftInput[K]) => onChange({ ...draft, [key]: value });
  const price = safePrice(draft);
  const field = (key: keyof DraftInput, maxLength = 500, placeholder?: string) => <input value={String(draft[key] ?? '')} onChange={e => set(key, e.target.value as never)} maxLength={maxLength} placeholder={placeholder} />;
  const area = (key: keyof DraftInput, maxLength: number, rows: number, placeholder?: string) => <textarea value={String(draft[key] ?? '')} onChange={e => set(key, e.target.value as never)} maxLength={maxLength} rows={rows} placeholder={placeholder} />;
  const updateLine = (index: number, key: string, value: string | number) => set('lineItems', draft.lineItems.map((line, i) => i === index ? { ...line, [key]: value } : line));
  return <div className="composer">
    <div className="page-heading"><div><p className="eyebrow">{request ? request.reference : 'A clear scope. A shared understanding.'}</p><h1>{firstTime ? <>Agree on the extra work<br className="desktop-break" /> before it starts.</> : request ? 'Write the next chapter.' : 'A new work request.'}</h1><p>{firstTime ? 'Put the details on paper. Share a private link. Keep the response together.' : 'Define the added work, then give your customer a clear decision.'}</p></div><div className="heading-note"><span className="notebook-rule" /><Icon name="book" size={27} /><span>THE WORK<br />COMES FIRST.</span></div></div>
    <div className="document-strip"><span><Icon name="lock" size={14} />Private until you publish</span><span>{request ? <Status status={request.status} /> : 'NEW REQUEST'}<span className="strip-dot">·</span>USD</span></div>
    <form onSubmit={e => { e.preventDefault(); onSave(); }}>
      <fieldset disabled={busy} className="editor-fieldset">
        <Section number="01" title="The people & the place" note="Let your customer know exactly which job this belongs to.">
          <div className="field-grid"><Field label="Business name">{field('businessName', 200, 'Your business name')}</Field><Field label="Business contact" hint="A phone number, email, or both.">{field('businessContact', 500, 'How your customer can reach you')}</Field><Field label="Customer name">{field('customerName', 200, 'Who is reviewing this request?')}</Field><Field label="Customer contact" optional>{field('customerContact', 500, 'Email or phone, if helpful')}</Field><Field label="Job title">{field('jobTitle', 300, 'A short, recognizable job name')}</Field><Field label="Job reference" hint="Provide a reference or a service address.">{field('jobReference', 100, 'Your job or work-order number')}</Field><Field label="Service address or job location" className="span-two">{field('serviceAddress', 500, 'Where the work takes place')}</Field></div>
        </Section>
        <Section number="02" title="What’s changing?" note="Be specific about the extra work, and where it stops.">
          <Field label="Additional scope">{area('scope', 10000, 4, 'Describe the extra work your customer is being asked to approve.')}</Field><Field label="Reason for the change">{area('reason', 3000, 2, 'What prompted this additional work?')}</Field><div className="field-grid"><Field label="Included work" optional>{area('includedWork', 5000, 3, 'Materials, labor, cleanup…')}</Field><Field label="Exclusions" optional>{area('exclusions', 5000, 3, 'Anything outside this request')}</Field></div>
        </Section>
        <Section number="03" title="The additional price" note="Only the added work. Enter USD amounts; use whole quantities.">
          <div className="line-items"><div className="line-item-head"><span>Description</span><span>Qty</span><span>Unit price</span><span>Amount</span><span /></div>{draft.lineItems.map((line, index) => <div className="line-item" key={index}><label className="line-description"><span className="mobile-label">Description</span><input aria-label={`Line ${index + 1} description`} value={line.description} onChange={e => updateLine(index, 'description', e.target.value)} maxLength={500} placeholder="Describe the work or material" /></label><label><span className="mobile-label">Quantity</span><input aria-label={`Line ${index + 1} quantity`} type="number" inputMode="numeric" min="1" max="999" step="1" value={line.quantity || ''} onChange={e => updateLine(index, 'quantity', Math.max(0, Math.trunc(Number(e.target.value))))} /></label><label className="currency-input"><span className="mobile-label">Unit price</span><span className="currency-prefix">$</span><input aria-label={`Line ${index + 1} unit price`} type="number" inputMode="decimal" min="0" max="1000000" step="0.01" value={line.unitPriceCents === 0 ? '' : line.unitPriceCents / 100} onChange={e => updateLine(index, 'unitPriceCents', Math.round(Number(e.target.value) * 100))} placeholder="0.00" /></label><span className="line-total numeric"><span className="mobile-label">Amount</span>{money(line.quantity * line.unitPriceCents)}</span><button type="button" className="icon-button remove-line" aria-label={`Remove line ${index + 1}`} onClick={() => set('lineItems', draft.lineItems.filter((_, i) => i !== index))}><Icon name="close" size={16} /></button></div>)}</div>
          <button className="text-button add-line" type="button" disabled={draft.lineItems.length >= 20} onClick={() => set('lineItems', [...draft.lineItems, { description: '', quantity: 1, unitPriceCents: 0 }])}><Icon name="plus" size={16} />Add line item <span className="muted">{draft.lineItems.length}/20</span></button>
          <div className="price-area"><p className="price-note">Enter any applicable tax yourself.<br />This tool does not determine tax rates.</p><div className="price-breakdown"><div><span>Subtotal</span><strong className="numeric">{price ? money(price.subtotalCents) : 'Check entries'}</strong></div><div><label htmlFor="tax-input">Entered tax</label><label className="currency-input tax-input"><span className="currency-prefix">$</span><input id="tax-input" type="number" inputMode="decimal" min="0" max="1000000" step="0.01" value={draft.taxCents === 0 ? '' : draft.taxCents / 100} onChange={e => set('taxCents', Math.round(Number(e.target.value) * 100))} placeholder="0.00" /></label></div><div className="price-total"><span>Additional amount <small>USD</small></span><strong className="numeric">{price ? money(price.totalCents) : 'Invalid'}</strong></div></div></div>
          {!price && <p className="form-error" role="alert">Check quantities and prices: use positive whole quantities (1–999), non-negative amounts, and a total no greater than $10,000,000.</p>}
          {price?.totalCents === 0 && <label className="checkbox-field"><input type="checkbox" checked={draft.zeroCostConfirmed} onChange={e => set('zeroCostConfirmed', e.target.checked)} /><span>I explicitly confirm this is a zero-cost scope change.</span></label>}
        </Section>
        <Section number="04" title="Timing & the finer details" note="Declare the timing honestly. Add only your own business terms.">
          <fieldset className="schedule-options"><legend>Schedule impact</legend>{([{ value: 'discuss', title: 'Timing to be discussed', note: 'The schedule is not yet agreed.' }, { value: 'none', title: 'No schedule impact stated', note: 'Your declaration for this extra work.' }, { value: 'impact', title: 'Specify a timing impact', note: 'Describe added days or another effect.' }] as const).map(option => <label key={option.value} className={`schedule-option ${draft.schedule.kind === option.value ? 'selected' : ''}`}><input type="radio" name="schedule" value={option.value} checked={draft.schedule.kind === option.value} onChange={() => set('schedule', { ...draft.schedule, kind: option.value })} /><span><strong>{option.title}</strong><small>{option.note}</small></span></label>)}</fieldset>
          {draft.schedule.kind === 'impact' && <Field label="Declared timing impact"><textarea value={draft.schedule.details} onChange={e => set('schedule', { ...draft.schedule, details: e.target.value })} maxLength={2000} rows={2} placeholder="State the specific timing impact for this extra work." /></Field>}
          <Field label="Your terms" optional hint="Plain text, shown exactly as entered to the customer.">{area('terms', 10000, 3, 'Add your own terms, if needed.')}</Field>
          <details className="private-notes"><summary><Icon name="lock" size={15} />Private owner notes <span>Never shown to your customer</span></summary><Field label="Private notes" optional>{area('privateNotes', 10000, 3, 'For your own reference only.')}</Field></details>
        </Section>
      </fieldset>
      {request && <p className="retention-note"><Icon name="book" size={15} />Hosted record available until <strong>{dateOnly(request.retainUntil)}</strong>. Export a copy for your records.</p>}
      {children}
      {validation.length > 0 && <div className="validation" role="alert"><strong>A few details are needed before publication.</strong><ul>{validation.map(item => <li key={item}>{item}</li>)}</ul></div>}
      {error && <p className="form-error" role="alert">{error}</p>}
      <div className="composer-actions"><div className="save-state" role="status"><span className={`save-indicator ${busy ? 'saving' : ''}`} />{busy ? 'Working with the server…' : request ? dirty ? 'Unsaved changes' : 'Draft saved on server' : 'Your draft is not saved yet'}</div><div className="action-row"><button className="button quiet" type="submit" disabled={busy}>Save draft</button><button className="button secondary" type="button" disabled={busy} onClick={onPreview}>Preview customer view<Icon name="arrow" /></button></div></div>
      <div className="publish-footer"><span>Review the customer view before sharing.</span><button className="text-button" type="button" disabled={busy} onClick={onPublish}>Publish request<Icon name="arrow" size={16} /></button></div>
    </form>
  </div>;
}
