import { describe, expect, it } from 'vitest';
import { blankDraft, calculatePrice, createSnapshot, decisionSchema, draftSchema, publicationErrors } from '../../shared/domain';

const valid = () => ({...blankDraft(),businessName:'Fictional Fence Co.',businessContact:'owner@example.test',customerName:'Sample Customer',jobTitle:'Side gate',jobReference:'SAMPLE-01',reason:'Customer requested gate access.',scope:'Add one side gate to the existing fence.',lineItems:[{description:'Side gate',quantity:1,unitPriceCents:35000}],schedule:{kind:'impact' as const,details:'One additional working day.'},privateNotes:'PRIVATE OWNER NOTE'});
describe('USD pricing and publication boundary',()=>{
  it('saves incomplete drafts but refuses their publication',()=>{expect(draftSchema.safeParse(blankDraft()).success).toBe(true);expect(publicationErrors(blankDraft()).length).toBeGreaterThan(4);expect(()=>createSnapshot(blankDraft())).toThrow();});
  it('recomputes integer prices and explicit entered tax',()=>{expect(calculatePrice({lineItems:[{description:'Gate',quantity:3,unitPriceCents:12345}],taxCents:101})).toEqual({subtotalCents:37035,taxCents:101,totalCents:37136,currency:'USD'});});
  it('rejects fractional, negative, oversized and unbounded amounts',()=>{for(const n of [-1,0.5,Number.MAX_SAFE_INTEGER])expect(()=>calculatePrice({lineItems:[{description:'x',quantity:1,unitPriceCents:n}],taxCents:0})).toThrow();expect(()=>calculatePrice({lineItems:[{description:'x',quantity:999,unitPriceCents:100000000}],taxCents:0})).toThrow();expect(draftSchema.safeParse({...valid(),lineItems:Array.from({length:21},()=>({description:'x',quantity:1,unitPriceCents:1}))}).success).toBe(false);});
  it('requires explicit zero-cost confirmation',()=>{const d={...valid(),lineItems:[{description:'No-cost change',quantity:1,unitPriceCents:0}]};expect(()=>createSnapshot(d)).toThrow('zero-cost');expect(createSnapshot({...d,zeroCostConfirmed:true}).totalCents).toBe(0);});
  it('excludes private notes and preserves declared timing and exact terms',()=>{const d={...valid(),terms:'Owner supplied plain text. <script>alert(1)</script>'};const snap=createSnapshot(d);expect(snap).not.toHaveProperty('privateNotes');expect(JSON.stringify(snap)).not.toContain('PRIVATE OWNER NOTE');expect(snap.schedule).toEqual(d.schedule);expect(snap.terms).toBe(d.terms);});
  it('does not accept browser totals or workspace authority in draft input',()=>{expect(draftSchema.safeParse({...valid(),totalCents:1}).success).toBe(false);expect(draftSchema.safeParse({...valid(),workspaceId:'another'}).success).toBe(false);});
  it('requires scope identities price and explicit impact details',()=>{expect(publicationErrors(valid())).toEqual([]);expect(publicationErrors({...valid(),schedule:{kind:'impact',details:''}})).toContain('Describe the declared timing impact.');expect(publicationErrors({...valid(),serviceAddress:'',jobReference:''})).toContain('A service address or job reference is required.');});
  it('requires typed names unchecked acknowledgment and useful requested changes',()=>{const base={action:'approved',respondentName:'Sample Customer',comment:'',acknowledged:false,idempotencyKey:crypto.randomUUID()};expect(decisionSchema.safeParse(base).success).toBe(false);expect(decisionSchema.safeParse({...base,acknowledged:true}).success).toBe(true);expect(decisionSchema.safeParse({...base,action:'changes_requested',comment:'Change'}).success).toBe(false);expect(decisionSchema.safeParse({...base,action:'changes_requested',comment:'Please widen the side gate.'}).success).toBe(true);});
});
